[project]
name = "english-word-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "smolagents[litellm]>=1.12.0",
    "structlog>=25.2.0",
    "typer>=0.15.2",
]
